services:
  - type: web
    name: shl-assessment-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app/main.py
    pythonVersion: 3.10.13
